import { useState, useEffect } from 'react'
import { Card } from '../../components/ui'
import { ShieldCheck, Upload, Loader2 } from 'lucide-react'
import { useVerifyKYC } from '../../hooks/useContractWrite'
import { useAccount } from 'wagmi'

export default function ContractorKYC() {
  const { address } = useAccount()
  const verifyKYC = useVerifyKYC()

  useEffect(() => {
    if (verifyKYC.isSuccess) {
      setStep('done')
    }
  }, [verifyKYC.isSuccess])

  const handleVerify = () => {
    // Demo mode handles the delay. In real mode, parsing proof.json happens here.
    // We send dummy proofs as this is just wiring up the hook signature.
    const proofA = [BigInt(1), BigInt(2)] as const
    const proofB = [[BigInt(1), BigInt(2)], [BigInt(1), BigInt(2)]] as const
    const proofC = [BigInt(1), BigInt(2)] as const
    const publicInputs = [BigInt(1)]
    verifyKYC.write(address as `0x${string}`, proofA, proofB, proofC, publicInputs)
  }

  return (
    <div className="max-w-xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-[#E8EDF5] tracking-tight">KYC & ZKP Onboarding</h1>
        <p className="text-sm text-[#8B95A8] mt-1">Verify your identity with zero-knowledge proof — your Aadhaar never touches the chain</p>
      </div>

      {step === 'done' ? (
        <Card className="text-center py-12 space-y-4">
          <div className="w-20 h-20 rounded-full bg-[#7F77DD]/10 border border-[#7F77DD]/20 flex items-center justify-center mx-auto">
            <ShieldCheck size={40} className="text-[#7F77DD]" />
          </div>
          <h2 className="text-xl font-bold text-[#E8EDF5]">ZKP Verified</h2>
          <p className="text-sm text-[#8B95A8]">Your Groth16 proof has been verified on-chain. You may now submit bids.</p>
          <div className="bg-[#0A0C10] border border-[#1E2530] rounded-lg p-3 text-xs font-mono text-[#7F77DD] text-left">
            proof_status: VALID<br/>
            circuit: kyc.circom (Groth16)<br/>
            on_chain: ZKPVerifier.sol ✓<br/>
            public_input: 0x3f8a...d219
          </div>
        </Card>
      ) : (
        <>
          <Card className="space-y-4">
            <h2 className="font-semibold text-[#E8EDF5]">Company Details</h2>
            {[
              { label: 'Company Name', placeholder: 'BuildRight Infra Pvt Ltd' },
              { label: 'GST Number', placeholder: '27AABCU9603R1Z8', mono: true },
              { label: 'CIN Number', placeholder: 'U45200MH2018PTC312345', mono: true },
              { label: 'Contact Email', placeholder: 'admin@buildright.in' },
            ].map(f => (
              <div key={f.label}>
                <label className="block text-xs text-[#8B95A8] mb-1.5">{f.label}</label>
                <input placeholder={f.placeholder}
                  className={`w-full bg-[#151A22] border border-[#1E2530] rounded-lg px-3 py-2 text-sm text-[#E8EDF5] placeholder-[#4A5568] outline-none focus:border-[#3B8BD4] transition-colors ${f.mono ? 'font-mono' : ''}`} />
              </div>
            ))}
          </Card>

          <Card className="space-y-4">
            <h2 className="font-semibold text-[#E8EDF5]">Aadhaar ZKP Proof</h2>
            <p className="text-xs text-[#8B95A8]">Upload your pre-generated <span className="text-[#7F77DD]">Groth16 proof</span> file. Your Aadhaar number is never revealed — only the validity is verified on-chain.</p>
            <div className="border-2 border-dashed border-[#1E2530] rounded-xl p-8 text-center hover:border-[#7F77DD]/40 transition-colors cursor-pointer group">
              <Upload size={28} className="text-[#4A5568] group-hover:text-[#7F77DD] mx-auto mb-3 transition-colors" />
              <p className="text-sm text-[#8B95A8]">Drop <span className="text-[#7F77DD]">proof.json</span> here or click to upload</p>
              <p className="text-xs text-[#4A5568] mt-1">Generated by snarkjs — kyc.circom circuit</p>
            </div>

            <button onClick={handleVerify} disabled={verifyKYC.isLoading}
              className="w-full bg-[#7F77DD] hover:bg-[#6b63cc] disabled:opacity-50 text-white font-semibold py-2.5 rounded-lg flex items-center justify-center gap-2 transition-all">
              {verifyKYC.isLoading ? <><Loader2 size={18} className="animate-spin" />Verifying on-chain...</> : <><ShieldCheck size={18} />Submit & Verify ZKP</>}
            </button>
          </Card>
        </>
      )}
    </div>
  )
}
