import { Card } from '../../components/ui'
import { Bot, ExternalLink, Download, ShieldCheck } from 'lucide-react'

const report = {
  id: 'A-2024-551',
  tender: 'T-2024-00142',
  generatedAt: 'Mar 10, 2024 14:45 UTC',
  ipfsHash: 'QmAuditReport1a2b3c4d5e6f7a8b9c0d1e2f',
  onChainTx: '0x7f3a21bc4e8d...9f21',
  content: `GovChain AI Audit Narrator — Report A-2024-551
Generated by Mistral-7B | Anchored on IPFS | Verified on Polygon Mumbai

═══════════════════════════════════════════════
EXECUTIVE SUMMARY
═══════════════════════════════════════════════

Tender T-2024-00142 (NH-48 Road Repair, Pune–Mumbai) has produced a 
highly anomalous bid from ShadyConstructions Corp that warrants immediate 
rejection and further investigation.

═══════════════════════════════════════════════
ANOMALY BREAKDOWN
═══════════════════════════════════════════════

1. BID PRICE OUTLIER
   Filed amount: ₹2.50 Cr
   Market median: ₹4.17 Cr
   Deviation: -40.1% (3.2σ below cluster mean)
   
   At this price point, fulfilling the stated scope of work would 
   generate a net loss of approximately ₹1.2 Cr for the contractor. 
   This pattern is consistent with "predatory underbidding" — a known 
   corruption vector where the contractor wins, then requests costly 
   change orders post-award.

2. WALLET FORENSICS
   Account age: 3 days prior to bid submission
   Prior transactions: 0
   ZKP proof status: INVALID (hash mismatch)
   
   A legitimate contractor would have an established on-chain history.
   The ZKP verification failure means we cannot confirm the contractor's
   Aadhaar-backed identity, violating the mandatory KYC prerequisite.

3. ML MODEL CONFIDENCE
   Isolation Forest anomaly score: 0.92 (threshold: 0.70)
   Feature importance: bid_amount (0.44), wallet_age (0.31), zkp_status (0.25)

═══════════════════════════════════════════════
RECOMMENDATION
═══════════════════════════════════════════════

ACTION REQUIRED: Reject bid B-2024-00892.
SECONDARY: Flag wallet 0xbad0...face for cross-contract review.
TERTIARY: Assign 2 bounty hunters to conduct independent review.

This report has been pinned to IPFS and its content hash stored on-chain
for permanent, tamper-evident audit record.`,
}

export default function ReportViewer() {
  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold text-[#E8EDF5] tracking-tight">AI Audit Report</h1>
          <p className="text-sm text-[#8B95A8] mt-1">LLM-generated plain-English analysis — anchored on IPFS</p>
        </div>
        <div className="flex gap-2">
          <a href="#" className="flex items-center gap-1.5 px-3 py-2 border border-[#1E2530] rounded-lg text-xs text-[#8B95A8] hover:text-[#E8EDF5] transition-colors">
            <ExternalLink size={14} />Polygonscan
          </a>
          <button className="flex items-center gap-1.5 px-3 py-2 bg-[#3B8BD4] hover:bg-[#2A75BB] text-white rounded-lg text-xs font-medium transition-colors">
            <Download size={14} />Download Cert
          </button>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-4">
        {[
          { label: 'Report ID', value: report.id, mono: true },
          { label: 'Generated', value: report.generatedAt, mono: false },
          { label: 'Model', value: 'Mistral-7B (Ollama)', mono: false },
        ].map(item => (
          <Card key={item.label} className="space-y-1">
            <div className="text-xs text-[#4A5568]">{item.label}</div>
            <div className={`text-sm font-semibold text-[#E8EDF5] ${item.mono ? 'font-mono' : ''}`}>{item.value}</div>
          </Card>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2">
          <Card className="space-y-4">
            <div className="flex items-center gap-2">
              <Bot size={20} className="text-[#7F77DD]" />
              <h3 className="font-semibold text-[#E8EDF5]">AI Narrative</h3>
            </div>
            <pre className="text-sm text-[#8B95A8] font-mono whitespace-pre-wrap leading-relaxed">{report.content}</pre>
          </Card>
        </div>
        <div className="space-y-4">
          <Card className="space-y-3">
            <h3 className="font-semibold text-[#E8EDF5] text-sm">On-Chain Proof</h3>
            <div className="space-y-2 text-xs">
              <div>
                <div className="text-[#4A5568] mb-1">IPFS Hash</div>
                <div className="font-mono text-[#7F77DD] break-all">{report.ipfsHash.slice(0,20)}...</div>
              </div>
              <div>
                <div className="text-[#4A5568] mb-1">On-chain TX</div>
                <div className="font-mono text-[#3B8BD4]">{report.onChainTx}</div>
              </div>
              <div className="flex items-center gap-1.5 text-[#1D9E75] font-medium mt-2">
                <ShieldCheck size={14} />
                <span>Tamper-evident ✓</span>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </div>
  )
}
